### ISSUE TITLE
Acknowledging Cod in Similar Project

### ISSUE THREAD

**Issue by tajmone** [namuol/cod#6]
Ciao @namuol!

I wanted to inform you that I'm acknowledging you and Cod in an app I've just published on GitHub (inside another project for now, it's still in Alpha):

- https://github.com/tajmone/PBCodeArcProto/blob/master/_assets/Doxter.pb

The acknowledgments can be found in the (self-generated) documentation (Live HTML link):

- https://htmlpreview.github.io/?https://github.com/tajmone/PBCodeArcProto/blob/master/_assets/Doxter.html#_acknowledgements

Although my app is quite a different beast from yours (not a fish at all), Cod has provided the sparkle of inspiration to find a custom solution to a problem I had been struggling with for quite some time. So I like to give credits where credits are due.

I didn't peak at Cod's source at all, I just took inspiration from its documentation, and the way language agnostic tags were being parsed into regions. That was enough to give me that _Eureka!_ moment where I could see the solution in front of me.

Best regards,

Tristano Ajmone (Italy)

**Comment by namuol** [comment]
Awesome to hear that @tajmone! Your comment brightened my day 😄

Cod was mostly an experiment for me; I never really had a chance to use it for anything serious, so the fact that it was a source of inspiration for a real project means it did more than I hoped for -- hope it doesn't steer you too far in the wrong direction 😅 Congrats on publishing Doxter 👏 

(Closing the issue for tidiness purposes, but good luck and keep up the great work!)
